// tslint:disable-next-line: variable-name
export let app_strings = {
    HOME_ROUTE: '/user',
    TWO_ZERO_ONE: '200',
    CRED_INCORRECT: 'Incorrect Credentials',
    NO_INTERNET_CONNECTION: 'No Internet Connection',
    ERROR_OCCURRED: 'An unexpected error occurred',
    IMAGE_REQUIRED: 'User image is required',
    INVALID_FORM: 'Invalid form submission',
    SUCCESS: 'Successfully done',
    DEF_IMAGE_URL: 'assets/images/def-person-m.jpg',
    UPDATED: 'Updated Successfully',
    PLEASE_UPLOAD_IMAGE: 'Please upload image atleast',
    pleaseUploadPurchaseOrder: 'Please Upload PurchaseOrder',
    pleaseUploadEstimateOrder: 'Please Upload Estimate order',
    FILE_SIZE: 20,
    FILENAME: 'report',
    XLS_EXTENSION: 'xls',
    CSV: 'csv',
    TWO_ZERO_ZERO: 200,
    EXCEED_WORD_LIMIT: 'Exceed word limit',
    CANT_UNDO: "Can't undo, user already exists",
    USER_NOT_EXISTS: 'User does not exists in records',
    INTEREST_MANDATORY: 'Interest is mandatory',
    PLEASE_SELECT_TIME_AS_WELL: 'Time is mandatory',
    Invalid:'Invalid form',
    NAME_NOT_EMPTY_CHECK: 'Name cannot be empty',
    SELECT_HOST: 'Select host ',
    DELETE_TYPE: 1,
    SUPERADMIN_TYPE: 1,
    PROMOTER_TYPE: 2,
    TEACHER_TYPE: 3,
    NGO_TYPE:4,
    STUDENT_TYPE:6,
    PROMOTER_NAME: 'promoter',
    ORG_NAME: 'org',
    TEACHER_NAME: 'teacher',
    STUDENT_NAME: 'student',
    USER_ROLES_ARR: {1: "superadmin", 2: "app promoter", 3: "teacher", 4: "ngo", 6: "student"},
    USER_ROLES_ARR_NAME: {"superadmin": 1, "app promoter": 2, "teacher": 3, "ngo": 4, "student": 6, "organization": 4},
    SELECT_INSTITUTE: "Please Select Institute",
    TREE_DATA: "Tree Data cannot be empty",
    IP: "https://api.ipify.org?format=json",
    EXPIRATION_LOGOUT: 'You have been logout because of Package Expiration or No Subscription',
    USER_IMAGE_PLACEHOLDER: 'assets/images/userimg.png',
    CLASS_ICON_PLACEHOLDER: 'assets/images/painting.png',
    MODELS: {
        /* const models = {
Users, Uploads, Options, Cart,
CartRelation, Enquiry, Card, Address,
Newsfeed, CMS, Onboarding, Products, Artisan
} */
        Faq: 'Faq', Aboutus: 'About us', 'Patch- message': 'Patch-message', Testimonial: 'Testimonial', Banner: 'Banner', USP: 'USP', Industries: 'Industries', artisan_group: 'artisan_group', product_group: 'product_group',
        purchaseOrder: 'po',invoice:'invoice',
        enquiries: 'enquiries',
        estimate: 'estimate',
        subAdminCategory:'subAdminCategory',
        users: 'users', uploads: 'uploads', options: 'options',
        support:'support',
        story: 'stories',
        awards:'awards',
        cart: 'cart',
        cartRelation: 'cart_relation', enquiry: 'enquiry', card: 'card',
        address: 'address',
        category: 'category',
        newsfeed: 'newsfeed', cms: 'cms', onboarding: 'onboarding',
        products: 'products', artisan: 'artisan',
        brand:'brand',
        type_of_store: 'type_of_store', aboutus_sample: 'aboutus_sample', customer_important_sample: 'customer_important_sample', catalogue: 'catalogue', career: 'carrer', Team: 'team', Blogs: 'blogs',
        returnPolicy: 'return', privacy: 'privacy'
    },
    ALPHABET_PATTERN: /^[A-Za-z ]+$/,
    URL_PATTERN: '(https?://)?([\\da-z.-]+)\\.([a-z.]{2,6})[/\\w .-]*/?',
    IMAGE_VALIDATION: 'Image is mandatory',
    errorMsg: {
        pleaseSelectOneArtisan: 'Please select atleast one artisan ',
        pleaseSelectOneProduct: 'Please select atleast one Product ',
        groupNameEXIST: 'Group Name already exist ',
    }
};
